apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "test"
  target:
    kind: Deployment
    name: frontend

images:
- name: ghcr.io/emadrasooli/frontend-app
  newName: ghcr.io/emadrasooli/frontend-app
  newTag: v20260919-1116-fe4db9a
