---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: staging
spec:
  encryptedData:
    database-url: AgCBI0qGJ9YLBgiHYojrBXEM9C7nmMvn/jh1LRvVNoRJLrcYBR/NFUN0z2zlQQPf7sW+ChvDepq+vXU1FSU+Ubyrqy/zXEGgHB87ilgw45J06MbhsvXbkvhhvgseADy6/wruXGUnMg/i0XGPtesxAQvtW6MOBbnxsf6Q4lbI7UaV6MoUbUt+fnfMZ3jJSPjFBVAln+4bmkzxuhWpOF2uasQORak+JYFq5ahVMC7pWzmfKvXfby7dKRP18jLxu5cvb5Du/MPbOAEHwQ3xleGoDYBOqZ7UndJRtnBp8OspULzdPM+ERohqWSQ4l+Vi6PTktx4RNFbazGA6gyktLBeqt06Gc8Y2pgYdAoPWHCjXrir5qWNNR12PjsMQmWRBq0fdk7WjxpDZ+7D/W8C/1QM8fany1l2taYDk8hJY/jCmpKaFQTzvD6p2d+1bYtAzF8PA9tBkFqGlETl9zHCATyCrvmOfPKoi+39oUVWlq6f4XtG0RMyZEsm2tFl5BzAvCwaD8dUQ+YUi317l97vCSYfeKF5ml/CLjrogvwML7IGbD+s3OahG746yh/psEBCIz5AXAI+beG9lf3xTvX7OPeLfQm95Q2HHeM4oBSq72bS95FBLz4wo+232+y3h6E2t86maL1Eku5zvBx62XfyrMuO6JUppnk3N4S0RdxH17ooCNv/DSJeNAff0Xz+KgieUXFCn4fKhNXsQnVlrkIbNn2UPIs/AzNd567JpkAEC5zKcDbPB1lblgyvRBcc72hostAQWi4Ec4TwwKxx7MsmLNNYqMoCtuSR9UPAQeVFxisJpGzQRVwVwZwSd6eWmkdAKA8XalLd+eW5gAIXhVw==
  template:
    metadata:
      name: backend-secrets
      namespace: staging
