---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: qa
spec:
  encryptedData:
    password: AgBgsqNni8qGX6z7Wr9ZeNWX7T+0SeZiZSkyREf/NvG4+CBsRg6hxl4gk5ONZQQGUZ77HdPskzTuzMlg3y0b2y0SoZQREh25XTbMrU04TWLoEczFQ3Iqo0DPdRTPN9XjOVGYog9LTRZF6a3j+CeM8UR3m4mxMymgT/4GI9uy9zPbFDbGLA1Ib8XbGg/4KmNtJSWIc8x+oZI6AlvYHyu6AoWak9I88iENEX7VRW/QtGD3zmS+GLBR0kX4MrnsEcr/PH6i5D04iaomsVJjJ3v3yxmvU78A2BMHhMfIbk9534CikD7MoFsrfS8WpF3YP4x5JCxVYjA2ZB7NK0GoB2vFDGlbjf+1qV1mgJvxIaYU0NlVz5n5Y0xQ5oodYwGKUREPWNf8+jGMHpOcW6g8Dc9jZSlraL2Fgdcw4jnlwhG94M+ln8zIfun9xpuvxSpXfHXkhn9AQHbUi5bVLSyzTp/sUrxnvvdYmtI3D85+P5VXxI8Je9wnHrlmSUImkw2wA814zpmA6NVllI60CQ3wTu+p21pKqLRdoD07YwYpPQfcVbwMbh2LJuwyr/VbJYqbpOtlBS6t5sCvFdat3AfqH5Lgt1MxGRGQ4BqCMhDu/h5dTKTSCxFnzWk8y9y7TQ8khjZgvqipghei//Vo/4rCLwlLKDKo4fUpNlXr6wlKjduOkeF6VqNIDHZBKKx2sQkUcJx3tPyjrFc6K2e3uqV4W6NATXTw2mJLY2vxTNTP0lOE6CNUfslyp6jUvoIs2GwF
    username: AgC2fkcHPbZqODtC0f/EBu7/Xmr7nKY1fybdH2r+Hzsh/zmFoAHpnhXdQZ5VtPe4S3tzzc2rzjRw3b9xWA8Zh2RAQE7sidnOHd8ICFwYao8F0qUJTC/ktu1+OT4HZRgqO6czaK95LhIqU1WXXrio3IaGbuscfzJ1Z9d3JIs5/SBU6U22oIkONf/5L6p/DtQx2Z2V1y83PIHoVZ19KpZiq/i8GdEmw/K9o1x8kSDJCPNi7GvQnKL1xCM/P4SiPa1kINdFNV/NoFhirppl3+YGbZEEa70fH6x2RqdTHLwkvhr/X84bw72o8yamLbpLnj1Oe52F0nJLPgvqWQN87ru3j12x/4B//vxVZd2GRPdUhHUbA/zvAgm1MNQ+IoHhX7pRAp5EczdbqG4vAR5qBfyhQlIPIKvpL1g7joigbmVp2FDmOmGqiEidDtTqroMNTLcVlLFcKSC6A1DUrCvKe+n/Wj5RDCtmEPP4pNGVeUMv3cqcKosSmnTiKk86iKXCz4j3A8PuYOU7xDQ2ZE79S5hxpS2kp2AvGGIYTaE06uYS/iYSGkdmGmId6gPtFfrWV9MqNh0R2O2ECMeU8IXqC2sxdIgMj7VJNA/UJy8bokdSZEvxeuWHlQY07tG4ELbsJwMNDajQbqSgkzvuRfaIL7cVsqyuWVMyhPka5mqILdTL5XiNGGdPQ83yNY37xrdqK/bsHR57eypsa9+GxLWYOHs=
  template:
    metadata:
      name: postgresql-secrets
      namespace: qa
