---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: prod
spec:
  encryptedData:
    password: AgCirgBCcgwR5O/yYPZ0ZzR8I+ktH1ZvVYpelvMe9bNTyUwVXw3iNN9laYVswbnDFkRklRmEZvbNqOnd9Ddx54v/2Uv6a+tLSdBTosL6v48XKkQmc/p3ih67mIbBVOyuPBLdsInz07KhilVseXscf/OEYFzCD5ebS9EUiVqBzJyrGMZK1OmqffCTbAgdXM0CUZsXxUlU/VqijMV+xlIKTlJk7ZQstnZEvBjPVU3XSFsdaWAvrj56EeKHh+a64ufflGp1lPAQ+yw2I4BK6+2zEHzRhS9nxpJmdc/dhqQ4drmYL9EF2j5Fg+d5i7Rcq8YbaUCYfIXsr/x6taDMqjeIRGihjaJux536oGJ8Wf8xwpKekT2ewmeuklwwVJrGCtfXIpv1o3MXXaVPPug612DFhOiwGklXYRqQtzhMS+iEyZR5q/agECzatlr5TzyGfPXq+wiiaCG2nVWChbftJA71lHzcj4yOLmcVuC4FgtUdJ9O9MoEZK48a9m+4/wM8pS4DqYQPEMl70M/z8BEgUeHPnZtWoV87Zj4qtdKpBNPMK941VAff9voHM47a2m3dOzd9Gc2oxa8C0ft78JRRylsvZZXf6RUz9dw/Eahf2iNYp1vBUgSvmLJgF56yaOnTt5r5s4I8tNmXQlLKu9VSPs7WnRGZA2r4y4MK746EDI+WYWODOzNWjGAeyP7xDsXzK0DVMG4OFskmETgYszxKm4cuhIa4G4uQ3U9sYtB2ZBZIPubmVcwpCuWGK/81TCm6
    username: AgByCp5j3adHlY0g8Gn9taSTuiGAUp1Rfmk8Vwahl1duCYDjUEoAhwpkv/vPwmj+dtXmHjasXkeW9vjJoS2YLGCO9lyqJBywPACWdctdIdTRqYTyMoNjk2mBQWFS7Rvoy2w2L5OBl+gjEa8SWQ5IOKI5Fpkw8CpReipmhX8OcRZ0smHdnCVAH9Aqu7PF2VTcieT3R5B/cBbUjisjr27WITrk+DSMb+TSibA4A/C90FHxhs1r4WzLSdb0F5n3+U+79pn7S13R2NjkU99FQ9YeC3lTbP1zsOZiq+Xp8OHYsxH4XIM6/eNrjPIhscdn8w7s8hoAyXFeJ/oCs5K+h7B3azNMuIyL1PYpVHi2FXB6z0p6UTKRc4mrWPlyUteTEzIuyUvfDSB/gvJveSioqyXgLgwX9KIU7fskzlwPntYD6agawdbHkEnHCBldalr0L+3OdRDWt5MDH8GrIgykMweIwIoAthED9rh4eGWVV0siHeOHzf81vEXlBYMHWlujVjSgv8MJGz6kwKzFIQeJikWfZfbntawUAuVLzWbWg/nwDetKVw0YDCm5CrUik9Z4xf73cXAVb2FdXLZ8I3DBYKIY8yZFQFdTzYfY3F3yigIfWWUJSAOJdKKwn+PSgvsdsQZdpj41vJEqzYDZYBAF9nLDygLXQ6ZDCjTTgZCK+roF79YpJcr4UxgravBwW3fcmtiLkFyJga5n/abR2jnln5GxMQ==
  template:
    metadata:
      name: postgresql-secrets
      namespace: prod
