---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: dev
spec:
  encryptedData:
    password: AgBaFLfwg2klZjpPOAzJFB60mhtNSeFUFodvPDUCXTrFwe0g8hGMG/Phn02yBGhLrq2mNH9J7HlaS7+VgfQZVSMCyDwMlUbwQeCyeYJU5B67cjmiOHr0MxEdDUykLSzkJ9Q/evTS+Jsd75T/f/mUasj+qIv3DAQ1fbOTkH3Ue3VlTp0Udq/8UCCNF3NVOOiFK1bCSYgqxyQ4xxtjnbqsjcrCNzbrb+hEaJxPYplWHh97TthG+IoY74Iqet7TAa1q0bYB+FnT9BeS8EhcgNgGEVPizB5pj25yjLbGbZcBah/TdJxJ27d/Y/g93gB3QbWoIk5udPQFYhSNs75ayLoKTI0fXafyMQmfSyXRtrDCF07GGfdSC9kkBoGHk/3jCbA413q9Z6y3v8v6F7oYVUs2JC8OFH5U0U6kIqNnJ8Xc2pxBdFjwvrqsZMJz3TpMbKm6EvtP5C1X8Fh1GH2sA2MTPq4RAyKFCBm0iwKikAlhGZfuTfpWuSomnTxfKGUm6MbVypt9kKJYP8H/7zE8e7dKwhLaYYJzqHtb5DYgLtgBd3D9wc7KSOVP2FxmyoeWFQBuXgOn1NDziLJCOcHEbPJW+AJCzcC2zsRG7TXjwCHMiI8i/riiOyj2BiSDtkQaMUhCJOFvFyj4LuroOxj94RIHdtq2MpLDLboBGQ0NQE8C8xelfJLwsXKLDj+Zqo7Wv3ywbOUGEtrozrdn4jVoC6WHaxcodMgbMz30u2B6owXi5aqPsxS+51HX29reciAR
    username: AgDJKaRIH1OrlPeGlvZ4Ch7yCBeOgKlD7OyUOHuarW5csknJlmeoAHSnLK/Cr8LNZ9IISmM2CDaECGF67h6C62gtBPeaGRUHGQ7zwuMo+ktMTk9HDgr8OEEY598UwCfs/0GwtzFbSNOo7BdIUBFSJYoY3/XFLAtQdbz02IE4vHbpfiqepy7Od0MUtVi6W25kg04eaBRPMyWnGX4nGOQbn+ZngI9+uvs7tYW77vwBhFSIhrpsUs6WacXtvQOzOjPFXdY1wv+nfhrzNROF5udz72Ny9B0vwNFQS+rIhRU4nISUK/6HirbE/5/YkspGCQlHRtOJoPYM0S8gRGSwgldOn7c1kXV2bkEdNkwmO3dgoNH+ros2NRjUj2Tui68E7GUa27tj3BT0NFmn4kjcaxzrVLgxM7+rRRKR3C1n0zf+CqP2jt2P4VcF4MKCzTyeMa1RUqi6/SiR9fLUbvfHy0uTZYPju5g47BrYF4LxoU9dSYdj6mwlv86EQSkmCGonuu3uo2c+yVNjHBfy90s+6qxbD2t+LHFmxblTl2Cls11NquP0B0GlBnWNLDHdtMG3V6hOV7bqlxTfXkO0QHTRSJtVVGBSoFwlGOZ1lsZA7uzXeXg44oRyMJSBGEDwCUSYRtKIKawbylooa8plQxAzxRWV+HW7nQ9ea2Wkdc5pIFizS4wuz2KzpgOdb6WiWDTj0ty5yPnwNolJa4JZmd8ifzfO
  template:
    metadata:
      name: postgresql-secrets
      namespace: dev
