---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: staging
spec:
  encryptedData:
    password: AgB/KltwFt1XdOpz08NXlqlk6byxwR8kTg2TvzUSPkaIfDpKtxqmkQMv2R2geat7g+Z+HDDLavwcSDQMTuPkclIPlyHV+w23Rd2+acVIiUiSqEJYE/jt66v3/cV2wZrmEpz+8ZaruSKUkcK2FnmMxlNqYhRekJbOABPlJIC2WRZU2fCwJcbSNPfGPU7BzT56cvfIzN9/OaagSHjYPCsmVMqCLsu5i8p+kpz7l6a6yM2r6SDw2Z8SkGuWesJpF7cGV4HONyudCLxMaYSbuURLqMVuwbMAPjcDg6sRNWaoF5nU3fqYlpc2ANyAI1RebOxFHXkoEa0qz+dE4RZMr84R/JBXmg+letysL98trcfq75ObVvJejIGxp9Si+pDcZuVk/fpjP4wiVpT/g8U1v+ZgssEgzZkdR//W6S8bc2tj0FNHDve1JgnYsyIaBdiK84DJ3ZPHcjyEpOQxH3pi9aN7k59gIR9XBMQVdXFmR/Oy/FJnSA1vcKya7zMyYc/z3W84KWoVf6dSWGKiW66TdVAKLotM8D+nadjbyBx9YYEDNy9PGDGi1mbWhNRczg6mf6YaVrZi4/a7KYy1fUumplhwVu1o5vsy5vMaEfzQvI5WWfK0BSs4YYD4zpv6TLsqTkpJagwWWkD+rhPH/EVYpMBL1nERNjByz7ddCBtqUrwSNUtBeCJcY8QbEIz3IpEph/PLbqDRAEZIZ7EK6U6Hq6BgpoZUeu28J+7kbUnIMF4hriJD5b6kESuhvpFpP2zS
    username: AgCHyoYyNa8z/Keegtr0DzGMk3gnIXyxpTwPSsPFhOYv2w5Ng25iDWokbCP+nktMnE2lJ8pBKKgM/CMZl7bb0F53naiPQm3XI3odb9p7x9QtMlCrf/39dBPtMHdmHQnH/gxOwnWgiII3fVhOCxB1RG1SFsE89A7aX557G+ZXGbmrihWioRrMnhejbNBSX6ng3oDgw3xBcQzysHR1Swh/b6t5zZskA9U+ss5QnbAMiHGZc/qVXv41aOFBGj7qumxlMx3pUkRrGJ254XlVAObMlOPwXSXL96AmFOd1tC72ZMZ3LhimOcHCWcSVOckD1CuuGR/3qb1v6W6c9qSPLye9RaexDdpbHGZ9zxBwK2NjjIkcYV6SYrx3sJro2U5qlwRoL0lAQX1wEuAciBAN/FLJ4Q/uRVQf1fq1BN6ZSBhwteQlCcVs0/ZCOp9k5oSUgCsiTfPsOHB+Tg35B90rY9/XajieoXqUKmzYit3erthA+6VUkKNYDABIWuPQ00hVHjJApYmTW1wgDjfpcqRXk+in2TQt7Eo7d7KscPeBlPiwek7eQbQ0lQoHXjrNMYd9EDS67LIk8kTif1GB7jhZZN1G4DbhRPUE6kAaGQBDn0xqpSEgArI7P3hYwnF0MKzpviJekxSUzg54G/onXIXQqDV4nRhItEoF3S4YSrB/W2Wi/L4a6emkqG9ShBvgAOhirtiRQomnk99fBtNYVJJOW+JQly62bQ==
  template:
    metadata:
      name: postgresql-secrets
      namespace: staging
