---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: qa
spec:
  encryptedData:
    database-url: AgBKDnas8tEJHfdF4wEOSh97Ug1Uqz2NnBRbe+psFFvZX0NeqnjwLIlVT/ecMRxhn33gr4ROwS8hWzp1HLd+ZxD4rpN8B9QSawAuyAGWMNrrz+ghgfFR7KQ+9cGRnetijdDdUKgRI1WVpc+n4HbNbAbofaSAv62DFlWpicE8o5jTszLOWT1v8i0n5hPFOQllwyk2TGWy3w2RYtJdY+vWIpJJb6IA1roWYXsArvGdy0YyQyP3R9YkUeRgY1Ouc0mfrK8A4vnwt8HUAT1oCvli3NubJUiUS0Dwr1BHWvDdnWSTFHebGC42YENLwSeq0AXmHxaxv9c/siyazjp0+U1rOLLNp1uxLYvAOCuglj7KtAgI0J+O0t3bWs5Ulpv15rFm+EUFP4so2wID09qUyjGrSe472oP14bgCsHJoi/x2GikP5NuoVuKtpP6PrUPn9IDZ1Vap3asyQlfDJ5LzrVFRFZ2VFycMSovzc/zPdiZzYNHGD45CwIOJ9RzGrPnwRwh8zG2oNZjzTrL2v5GNClCzRgc9riS1YHqyr5VhhOMQ8pkmuiBcJA4UlDYtdZ3ZnBPnXbmtbe9XG9PLswm+idXS6PHplBPVjiVQMKdOUnWOFB0OHQ9qFHl0eA0POe60X3I/kjmCEHyZw10ABkL4737Zu1W7Z08J0+KOwAMmSCYWtVCL3Po114z36cDLTYy/Zg9lFLcGdjz2B2uG1aDRbwTdtgt3JV7Op1xcwSW+aBu+rIWrc1z/yjz5Uq3RZjrvjalMErOUCIQeIDZh06u6xwZBUdMLIbvhODzDoGfp7723M5U9vkat3WhwerfDsUcN5lkXH97ufJY=
  template:
    metadata:
      name: backend-secrets
      namespace: qa
