apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: qa
    app: backend
spec:
  project: gitops-thesis
  source:
    repoURL: https://github.com/emadrasooli/infra-code.git
    targetRevision: main
    path: apps/backend/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
