---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: prod
spec:
  encryptedData:
    database-url: AgDSyhS1mW6/6D0NLRvDiDclfQRqR6OXtinE9AriOkyK3bk3PaiY7qCGsJOc6/RtAfPN2274e3kr4EcnwGbLyWQWaqSj4KFt0/SfGwBhfqlqZFOWtfLBA8LyOJm9Qj2oP2DLOKHdMWIJG/ZTSXmDiRDTDOtpHZCSsh3h7epUa/bnYk4Ee3Fne++f9DbvOCbmJCdWGBg0n1e86fztlElIlKkfOEl8oM4Qns9+KsEstsKBp7zNKha5L4dUqtveMxGbGKDC+/Izjpp+D6L9Km0u7y3AY/jesf1LPJQGrtuwCxAdhTrCVpYt3BJMYRNdbAPOqkZSXTY7IHoWDC3CAVxe2jep0RA/o753Nht/CjD405CNgL+P9YvXORhFXYQhxnpJX4CKyAicdyP+yzuUvrH4Ht462DqhCGraFyJ7DYYeeS/IMkio65ToS6USeI/6TD2c1vpYS0VAp6AGZs3giscfnuBTSUuVgCbZKQDFICqalNUVyWmpbCqKsAAs1WbG617KYas4Xy83ya7U7pKupHrpHHbpw7fj4SccaDNoPhc5pmZYb+quRiEraRc7UM4pLYhF2JyE+a1u98GN5r1cb06ApTpcUNlNQbOPtirMb7oKPY3tYNRYS5pX7FCGcenFfty7VCywG8dLj7LDTgzSHp/K7qyrWB/8jc7iX3PHDWC7lE3Cw+/XW6IOSFkvCO8DCpytKHuMYAqpD99jIk2fZaIRkjqv3MDqcOmpyZw4Z2GLj1rCwu64KIB1/4fbybdVltPQt/22j6hdJPccBI+df5/GU9mAFUgYL8Vm+5apjA4rn1xHZEk+oevqAkN/QUbSyOmD33K0DeCH6g==
  template:
    metadata:
      name: backend-secrets
      namespace: prod
