---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: qa
spec:
  encryptedData:
    database-url: AgApEdGWr29cl02ZpZTtHf0ll4f5zJVDY3HXwHJ08h44Ru1CUtuRoY8vicyhwYnrWTqCwLPEj553Ppq6Gfou7TE2ahPBY0Oi+PgTaiwZMcwhQj9RsdVRPgrzzSMEzWgS2Sm+oAZC4QJb2OedJyfMzkFPa7jpvqBbFsRZyWYEG9rpMGn7ceMYubq60FVTOlFJCkgpfzFjdShXkTXmUYKeTR+gSsjczJIgEuhaXtnPUITGCNdelRH5ONIVdVLmAqkCPgc3W4PqltWMzZIHV69EiyN3ibqzUbEP92wMcTA70qCyD7tX0DbdI+sv5WC+HE3H529UiERV8lLx7s8VS6vL4rFLybmVXK+4AN9Hg268TElmGmg/3Soa4ZzlDPd7WZzlHqQt0tcZGI3K7B7+zFrnglICEOOnhi1YDBs2+3gnxyY4jGvh8F2cwUvJrWv4TlDqZGhkqj7o5V2Tbj3sXDe2yZzAoVsxFfM6Bd24MWc0VI49byTdb1GLYvixLIybF1vVRaTfE7Uf0xibqZ15q8SoY2Swe7555Pi34lugpWmvHc5dWoEvEJ/+5f1FuBdGovHQTLmszuvjZC5mjqHtNElsxHWFbZHqhNM6fXHM7UZSnbwVJhAleEIJH9i+U7rndR+aLJ0WwjTqiBtqtRMbIf1bpN78eJwKrdb7kb5cyo6L/qeEKeHmPKFDEMwrK9sa4BC2VaGOeuhLR5eXdsrhlhkb/vwbG+FAytLpapke0X1xJ0Kju03b3OjOGN+6SWjbj8kUdU+WQf9zR4f/ziSO+aaDhus=
  template:
    metadata:
      name: backend-secrets
      namespace: qa
