---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: dev
spec:
  encryptedData:
    database-url: AgArqn22r5Chm4/xHB/WTz3pzzWi4a9ZMD78umOmPoOLgzVx2nGUNRN3ymRf1+EDbZv6pmNVqamCUnoYkjGm0GqiHgWlS1V4ITl8bOWXG010yzc6O4eV0ctRZe+rUjNtpaBAbKmvYYGNpWtsEO7Y/OuRF7reZ6oGu9/MIKoaQoAbtM3/1i9hAdRloA5XwSZ/w3eju8YW1zU6PA1CqoE7o4GIvnkY/CR8sxQOCNVSz51MZHO5eJ6uKc/xrpMr65lr8g3lep6gVR3H2+04268vbJDIJQs8mjxuLShK9Cv8QZw4aKXU3cAKgKqYIvVrVRdnARO/99N+G+SLAEfeZiH3T6iCNV4YBl/sT56HIDrJqsj+QcjcDtvBmETTQbf7MMU2x8KqQTdWFTZ9LdiF91QvSFAlLqcmKwrQlJdDBuvU9TYvWSBZJObA4m0b8zGQP194MYULfGKx/AWgqZeAGy1sQ4JGzZVTQ11uFx8FyeRL4TN1mnDFph9ImgUBkUfiwaD+AnfkO7Ej213j9o1kXGEIiGjNJa0B/fIBeOiu+OkI8rLdCNihDq8T4nzwssM6JheOr6NVuDOB1jEmd+YQ2VeP4w42NiG/TbPy9vtiSURygydaKfIxRgRRVoYdbVPCMtp/1NHuxpNoFvIzPi7DlzBS/JvFcqcX4zEG6usIuJFxOODb6ULQHXcX0AffuyspLyDDMLRFPMpSFPmzOdmRYxCeL9/ARE1sPQWoaWIzgrunjNuUfel5DbWUJTUgh3AdHvai8L2CrV49NE/4SCDVGWihDQI=
  template:
    metadata:
      name: backend-secrets
      namespace: dev
