---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: dev
spec:
  encryptedData:
    database-url: AgAU+NCVahNgdRTnQyJBP1etYjIZ3M12kgNNP0u1eld+2wCbqjrh+vfISTWiqLrTwrUga/GA0cGZkHJpRlsKPi6vD6X2R5jsGc/5IVLNv7ZOn+roJod9pkdyAOEq6pXH+n1v8+1a7hzY4D2aZvmtVMGC5+p8aykqWqV8RhjWGocjrmocoJ8lbmdO/5eWa4Ztapjh7tFF4tIxWejdz3HPQqewZ3geJj8wDgpKIfwrZhwvHjHVT0W4UaRj2FinQKBE3pZLTxAf8sxnxtvnS0yKOKUyDDKPjo1Ng5BHjvqlldxqJdDwq502+n2eyf0JunTHjmk63ikqtk5BOLt1kTPG3Llg8rb3mZ224ujNa3ha1qzJJqAERGDGNvOjjcCWuTHGJ2JRMweoxucWWzCskLhEHgO74FyNUkAo6RXrGu6ic43XpbSoPw5kmVlbAcIkzC1/j7Ip/3oWDYfQuxx3s3lxpwb48N2T+Et+kp/eP5yeXhZpCzdnNS3gj7879OgTBl3GRZYnKhR9QY8XmPfaCq5RT39kxKjf5bIJ0XHvMktjvAo8RQ1KsGCyaGIdanOr1ItzLV7gPJIWma7EmhqBZ1PdvJAmRCWLuJcqactWZPW4WbZUB9f2Rvmx+g8eGs1Axghq8TvsSAPdKPrP/jlo5ks9KuRn6+yyuUkP4z/wzIySi1A2h9ufp43xxyDzx+ByYKVdKsXMvw9a83yIuS9zRbqZGQgYzn3wChu64k3oGc+psUmG6m1zju30Qff1b8iTpyqq5Tu/irhPVbyGhPyR0HLkORymOgzu0mD0uW0Nj+Nif0CMlGlK+If3832JuxDua22AHOPof0F3
  template:
    metadata:
      name: backend-secrets
      namespace: dev
